# KREDENSIAL GOOGLE SHEETS SERVICE ACCOUNT
# Masukkan data service account Google Cloud Anda di bawah ini.
# Jika kredensial belum diisi atau tidak valid, aplikasi otomatis menggunakan mode offline/cache lokal
# dan dapat langsung disinkronkan ke Google Sheets kapan saja.

[google_apps_script]
gsheets_webhook_url = ""

[app_config]
admin_pin = "11223344"
